from contextlib import contextmanager

from sqlalchemy import create_engine

from .config import settings


engine = create_engine(settings.database_url, future=True, pool_pre_ping=True)


@contextmanager
def get_connection():
    with engine.begin() as connection:
        yield connection


MIGRATION_SQL = """
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    task_group TEXT NOT NULL DEFAULT '',
    employee TEXT NOT NULL DEFAULT '',
    control TEXT NOT NULL DEFAULT 'stop' CHECK (control IN ('play', 'stop')),
    dependency BIGINT NULL REFERENCES tasks(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'idle' CHECK (status IN ('idle', 'running', 'success', 'error')),
    notifications BOOLEAN NOT NULL DEFAULT FALSE,
    logs TEXT NOT NULL DEFAULT '',
    comment TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS task_properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL UNIQUE REFERENCES tasks(id) ON DELETE CASCADE,
    launch_day TEXT NOT NULL DEFAULT '',
    launch_time TEXT NOT NULL DEFAULT '',
    end_day TEXT NOT NULL DEFAULT '',
    end_time TEXT NOT NULL DEFAULT '',
    file_type TEXT NOT NULL DEFAULT 'SQL' CHECK (file_type IN ('SQL', 'PY', 'BAT')),
    connection TEXT NOT NULL DEFAULT '',
    notification_channel TEXT NOT NULL DEFAULT '',
    notification_value TEXT NOT NULL DEFAULT '',
    cron_expression TEXT NOT NULL DEFAULT ''
);


CREATE INDEX IF NOT EXISTS idx_task_properties_task_id ON task_properties(task_id);
"""


def run_migrations() -> None:
    with get_connection() as connection:
        for statement in [s.strip() for s in MIGRATION_SQL.split(";") if s.strip()]:
            connection.exec_driver_sql(statement)
